- name: Install influxdb exporter
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/

- name: Giving permission to influx_stats_exporter_linux_amd64
  file:
    path: /usr/local/bin/influx_stats_exporter_linux_amd64
    mode: 0755

- name: Template prometheus-influxdb-stats-exporter.service.j2
  ansible.builtin.template:
    src: prometheus-influxdb-stats-exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
    owner: "{{prometheus_user}}"
    group: "{{prometheus_user}}"
  notify:
    - Restart influxdb_exporter
    - Reload daemon

- name: Ensure influxdb exporter is running
  service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: yes
