- name: Add grafana repo key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Add grafana repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install grafana
  apt:
    name: grafana

- name: Copy grafana.ini template
  ansible.builtin.copy:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: 
    - Restart grafana

- name: Ensure grafana is running
  service:
    name: grafana-server
    state: started
    enabled: true

- name: Copy datasource.yaml to grafana
  ansible.builtin.copy:
    src: datasource.yaml
    dest: /etc/grafana/provisioning/datasources/datasource.yaml
  notify: Restart grafana

- name: Copy dashboard.yaml to grafana
  ansible.builtin.copy:
    src: dashboard.yaml
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart grafana

- name: Creates directory for dashboard
  file:
    path: /var/lib/grafana/dashboards
    state: directory

- name: Copy grafana dashboard's JSON
  ansible.builtin.copy:
    src: main.json
    dest: /var/lib/grafana/dashboards/main.json
  notify: Restart grafana

- name: Copy grafana syslog.json dashboard
  ansible.builtin.copy:
    src: syslog.json
    dest: /var/lib/grafana/dashboards/syslog.json
  notify: Restart grafana

- name: Copy grafana mysql.json dashboard
  ansible.builtin.copy:
    src: mysql.json
    dest: /var/lib/grafana/dashboards/mysql.json
  notify: Restart grafana
