- name: Install uwsgi & uwsgi-plugin-python3
  apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3

- name: Install python3-pymysql on app server
  ansible.builtin.apt:
    name: 
      - python3-flask-sqlalchemy
      - python3-pymysql

- name: Create uwsgi directory in vm
  ansible.builtin.file:
    path: /etc/uwsgi/apps-enabled/
    state: directory
    owner: agama

- name: Copy agama.ini to vm directory
  ansible.builtin.template:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/
    owner: agama
    mode: '0644'
  notify: 
  - Restart uwsgi    

- name: Ensure uwsgi service is started unconditionally
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes
  
  
  


