- name: Install uwsgi & uwsgi-plugin-python3
  apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3

- name: Install python3-pymysql on app server
  ansible.builtin.apt:
    name: 
      - python3-flask-sqlalchemy
      - python3-pymysql

- name: Ensure uwsgi service is started unconditionally
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes
  
  
  


