---
- name: Web server
  hosts: web_servers
  become: yes
  roles: 
    - users
    - agama
    - uwsgi
    - nginx

  handlers:
    - name: Restart uwsgi
      ansible.builtin.service:
        name: uwsgi
        state: restarted

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
