---
- name: Init
  hosts: all
  become: yes
  roles:
    - init

- name: Database server
  hosts: db_servers
  become: yes
  roles:
    - mysql
    
- name: Web server
  hosts: web_servers
  become: yes
  roles: 
    - users
    - agama
    - uwsgi
    - nginx

- name: DNS server
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind
    - bind_exporter

- name: VM 1
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - copyrole
    - mysql_exporter
    - nginx_ exporter

- name: Node exporter
  hosts: node_exporters
  become: yes
  gather_facts: no
  roles:
    - node_exporter

- name: prometheus
  hosts: prometheus
  become: yes
  gather_facts: no
  roles:
    - prometheus
    



