---
- name: Collect info about all VMs
  hosts: all
  gather_facts: yes
  tasks:
    - setup:

- name: Init
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - init
    - backup

- name: Database server
  hosts: db_servers
  become: yes
  gather_facts: yes
  roles:
    - mysql
    - mysql_backup

- name: Web server
  hosts: web_servers
  become: yes
  gather_facts: yes
  roles:
    - users
    - agama
    - uwsgi
    - nginx

- name: DNS server
  hosts: dns_servers
  become: yes
  gather_facts: yes
  roles:
    - bind
    - bind_exporter
  tags:
    - DNS

- name: prometheus
  hosts: prometheus
  become: yes
  gather_facts: yes
  roles:
    - prometheus

- name: VM 1
  hosts: web_servers
  become: yes
  gather_facts: yes
  roles:
    - mysql_exporter
    - nginx_exporter

- name: Node exporter
  hosts: node_exporters
  become: yes
  gather_facts: yes
  roles:
    - node_exporter

- name: Grafana
  hosts: grafana
  become: yes
  gather_facts: yes
  roles:
    - grafana
  tags:
    - GRAFANA

- name: Influxdb
  hosts: influxdb
  become: yes
  roles:
    - influxdb
    - influxdb_backup
  tags:
   - INFLUXDB

- name: pinger
  hosts: pinger
  become: yes
  roles:
    - pinger
  tags:
    - PINGER

- name: Rsyslog
  hosts: rsyslog
  become: yes
  roles:
    - rsyslog
  tags:
    - RSYSLOG

- name: Influxdb Stats Exporter
  hosts: influxdb_stats_exporter
  become: yes
  roles:
    - influxdb_exporter
  tags:
    - INFLUXDB_STATS_EXPORTER
