---

- name: Collect info about all VMs
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - setup:

- name: Init
  hosts: init
  become: yes
  roles:
    - init

- name: Backup
  hosts: backup
  become: yes
  roles:
    - backup 

- name: IPtables
  hosts: iptables
  become: yes
  roles:
    - iptables

- name: Bind9 DNS server
  hosts: dns_servers
  become: yes
  roles:
    - bind

- name: MySQL database server
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - mysql_backup

- name: Docker
  hosts: docker
  become: yes
  roles:
    - docker

- name: Nginx
  hosts: nginx
  become: yes
  roles:
    - nginx

- name: Agama web server
  hosts: web_servers
  become: yes
  roles:
    - agama
    - uwsgi

- name: Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus

- name: InfluxDB and Telegraf
  hosts: influxdb
  become: yes
  roles:
    - influxdb
    - influxdb_backup

- name: Pinger
  hosts: pinger
  become: yes
  roles:
    - pinger

- name: Rsyslog
  hosts: rsyslog
  become: yes
  roles:
    - rsyslog

- name: Haproxy
  hosts: haproxy
  become: yes
  roles:
    - haproxy

- name: Keepalived
  hosts: keepalived
  become: yes
  roles:
    - keepalived

- name: VM1 exporters
  hosts: vm1&2_exporters
  become: yes
  roles:
    - node_exporter 
    - nginx_exporter 
    - bind_exporter 
    - mysql_exporter

- name: VM3 exporters
  hosts: vm3_exporters
  become: yes
  roles:
    - node_exporter 
    - nginx_exporter 
    - bind_exporter 
    - influxdb_exporter

- name: Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana

- name: Rsyslog Slaves
  hosts: rsyslog_slaves
  become: yes
  roles:
    - rsyslog
