---
- name: Collect info about all VMs
  hosts: all
  gather_facts: yes
  tasks:
    - setup:

- name: Init
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - init
    - backup
  tags:
    - init
    - backup

- name: iptables
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - iptables

- name: Bind9 DNS server
  hosts: dns_server
  gather_facts: no
  become: yes
  roles:
    - bind
  tags:
    - bind
    - exporter
    - grafana
    - webserver

- name: Docker instances
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - docker
  tags:
    - docker

- name: Install nginx on all machines
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - nginx
  tags:
    - exporter
    - webserver

- name: upload rsyslog conf
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - rsyslog
  tags:
    - rsyslog

- name: Database server
  hosts: db_servers
  gather_facts: no
  become: yes
  roles:
    - mysql
    - mysql_backup
  tags:
    - mysql
    - backup
    - webserver
    - db

- name: Ansible webservers 
  hosts: agama
  gather_facts: no
  become: yes
  roles:
    - agama
    - uwsgi
  tags:
    - agama
    - webserver

- name: Install and configure prometheus-node-exporter
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - node_exporter
  tags:
    - exporter

- name: Install and configure prometheus
  hosts: prometheus
  gather_facts: no
  become: yes
  roles:
    - prometheus
  tags:
    - prometheus
    - grafana

- name: Install and configure bind-exporter
  hosts: dns_server
  gather_facts: no
  become: yes
  roles:
    - bind_exporter
  tags:
    - exporter

- name: Install and configure mysqld-exporter
  hosts: mysqld_exporter
  gather_facts: no
  become: yes
  roles:
    - mysql_exporter
  tags:
    - exporter

- name: Install and configure nginx-exporter
  hosts: nginx_exporter
  gather_facts: no
  become: yes
  roles:
    - nginx_exporter
  tags:
    - exporter

- name: Install and configure grafana
  hosts: grafana
  gather_facts: no
  become: yes
  roles:
    - grafana
  tags:
    - grafana
    - g

- name: Install and configure influxdb
  hosts: influx_db
  gather_facts: no
  become: yes
  roles:
    - influxdb
    - influxdb_backup
  tags:
    - influx
    - backup
    - grafana
    - db

- name: Create pinger and configure it
  hosts: influx_db
  gather_facts: no
  become: yes
  roles:
    - pinger
  tags:
    - pinger
    - grafana

- name: Create influxdb_stats_exporter
  hosts: influx_db
  gather_facts: no
  become: yes
  roles:
    - influxdb_exporter
  tags:
    - influxdb_exporter
    - exporter

- name: Install and configure loadbalancer
  hosts: loadbalancer
  gather_facts: yes
  become: yes
  roles:
    - keepalived
    - haproxy
  tags:
    - balancer