{
 "title": "mySQL1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL Slave",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running"
    }
   ]
  },
  {
   "title": "MySQL IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running"
    }
   ]
  },
  {
   "title": "MySQL read only",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only"
    }
   ]
  },
  {
   "title": "MySQL ids",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(node_memory_Active_bytes[1m])"
    }
   ]
  },
  {
   "title": "bind9 status + dns queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])"
    }
   ]
  },
  {
   "title": "mysql status + amounts of selects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total[1m])"
    }
   ]
  },
  {
   "title": "nginx status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "InfluxDB health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])"
    }
   ]
  }
 ]
}