- name: Restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: Reload Remote Name Daemon Control
  shell: "systemctl daemon-reload"

- name: rndc reload
  ansible.builtin.command:
    cmd: rndc reload
  
