- name: Create directory /opt/agama if it does not exist
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: root
    group: root
    recurse: true

- name: Install dependencies
  apt:
    name: python3-flask-sqlalchemy
    update_cache: yes

- name: Install agama application 
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    force: yes
    dest: /opt/agama
    mode: 0755
