- name: Create directories for backup&restore
  file:
    path: /home/backup/{{ item }}
    state: directory
    owner: backup
    group: backup
    mode: '0755'
  loop:
    - backup
    - restore

- name: Create user for backup
  user:
    name: backup
    shell: /bin/bash
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Install duplicity
  apt:
    name: duplicity

- name: Template backup-server-ssh-key to known hosts
  template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: root
    group: root
    mode: 0644
