- name: Restart nginx_exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: restarted

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Reload systemd
  shell: systemctl daemon-reload
