---
  - name: Systemctl daemon-reload
    shell: "systemctl daemon-reload"
    
  - name: Restart keepalived
    service:
      name: keepalived
      state: restarted
      enabled: yes
      
  - name: Restart keepalived_exporter
    service:
      name: keepalived-exporter
      state: restarted
      enabled: yes
